theme: jekyll-theme-cayman
title: Simple OCR
description: An open-sourced OCR Application that uses Tesseract OCR.
show_downloads: true
github:
  zip_url: https://github.com/kennysmoothx/simple-ocr/releases